### ISSUE TITLE
No module named 'ComfyUI-Fluxtapoz.utils.const'

### ISSUE THREAD

**Issue by Amazon90** [logtd/ComfyUI-Fluxtapoz#59]
File "D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz\__init__.py", line 9, in <module>
    from .nodes.rf_edit_sampler_nodes import FlowEditForwardSamplerNode, FlowEditReverseSamplerNode, PrepareAttnBankNode, RFSingleBlocksOverrideNode, RFDoubleBlocksOverrideNode
  File "D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz\nodes\rf_edit_sampler_nodes.py", line 7, in <module>
    from ..utils.const import DEFAULT_DOUBLE_LAYERS, DEFAULT_SINGLE_LAYERS
ModuleNotFoundError: No module named 'ComfyUI-Fluxtapoz.utils.const'

Cannot import D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz module for custom nodes: No module named 'ComfyUI-Fluxtapoz.utils.const'
```
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-12 14:01:24.153661
** Platform: Windows
** Python version: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
** Python executable: D:\ComfyUI\venv\Scripts\Python.exe
** ComfyUI Path: D:\ComfyUI
** Log path: D:\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use
  10.9 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 16106 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: D:\ComfyUI\web
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz\__init__.py", line 9, in <module>
    from .nodes.rf_edit_sampler_nodes import FlowEditForwardSamplerNode, FlowEditReverseSamplerNode, PrepareAttnBankNode, RFSingleBlocksOverrideNode, RFDoubleBlocksOverrideNode
  File "D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz\nodes\rf_edit_sampler_nodes.py", line 7, in <module>
    from ..utils.const import DEFAULT_DOUBLE_LAYERS, DEFAULT_SINGLE_LAYERS
ModuleNotFoundError: No module named 'ComfyUI-Fluxtapoz.utils.const'

Cannot import D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz module for custom nodes: No module named 'ComfyUI-Fluxtapoz.utils.const'
### Loading: ComfyUI-Impact-Pack (V8.0.1)
[Impact Pack] Wildcards loading done.
Total VRAM 12282 MB, total RAM 16106 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Version: v0.3.7-18-g3dfdddcc | Released on '2024-12-11'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Nvidia APEX normalization not installed, using PyTorch LayerNorm
[ReActor] - STATUS - Running v0.5.2-a1 in ComfyUI
Torch version: 2.5.1+cu124
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Nvidia APEX normalization not installed, using PyTorch LayerNorm

[rgthree-comfy] Loaded 42 fantastic nodes. 🎉

Please 'pip install apex'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_AdvancedRefluxControl
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Detail-Daemon
   0.0 seconds: D:\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-InstantX-IPAdapter-SD3
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-IPAdapter-Flux
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper
   0.0 seconds: D:\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_LayerStyle_Advance
   0.1 seconds: D:\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.1 seconds: D:\ComfyUI\custom_nodes\SDXL_EcomID_ComfyUI
   0.1 seconds: D:\ComfyUI\custom_nodes\comfyui-reactor-node
   0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.1 seconds: D:\ComfyUI\custom_nodes\comfyui_face_parsing
   0.2 seconds (IMPORT FAILED): D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz
   0.4 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: D:\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
   0.5 seconds: D:\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.6 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.2 seconds: D:\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

**Comment by TobiTomatoe** [comment]
Yep! Same issue

**Comment by msola-ht** [comment]
Yep! Same issue

**Comment by mionax** [comment]
Yep! Same issue

**Comment by coddz** [comment]
Same issue.

maybe const.py is not commited?

**Comment by Piscabo** [comment]
Me Thee:
Traceback (most recent call last):
  File "E:\AI_Files\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz\__init__.py", line 9, in <module>
    from .nodes.rf_edit_sampler_nodes import FlowEditForwardSamplerNode, FlowEditReverseSamplerNode, PrepareAttnBankNode, RFSingleBlocksOverrideNode, RFDoubleBlocksOverrideNode
  File "E:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz\nodes\rf_edit_sampler_nodes.py", line 7, in <module>
    from ..utils.const import DEFAULT_DOUBLE_LAYERS, DEFAULT_SINGLE_LAYERS
ModuleNotFoundError: No module named 'ComfyUI-Fluxtapoz.utils.const'

**Comment by TobiTomatoe** [comment]
Hey, while I'm here let me ask some of you guys something. I know this is off topic and doesn't belong here, but it drives me insane. I already added a new issue at comfyanonymous/ComfyUI. I update comfyUI on a daily basis and like three days ago, flux-def is loading extremely slowly, to the point where it is pretty much unusable. Anyone experiencing the same?

**Comment by MJvanAdrichem** [comment]
Same issue here.

**Comment by 925-Studio** [comment]
Same issue after updated this custom_node.

**Comment by logtd** [comment]
Hi, sorry for the issue folks, this has been fixed

**Comment by 925-Studio** [comment]
> Hi, sorry for the issue folks, this has been fixed

Another issue appears after you latest update. Still can't import your custom_node.

```bash
Traceback (most recent call last):
  File "/home/silver/Playground/AI/ComfyUI/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/silver/Playground/AI/ComfyUI/custom_nodes/ComfyUI-Fluxtapoz/__init__.py", line 9, in <module>
    from .nodes.rf_edit_sampler_nodes import FlowEditForwardSamplerNode, FlowEditReverseSamplerNode, PrepareAttnBankNode, RFSingleBlocksOverrideNode, RFDoubleBlocksOverrideNode
ImportError: cannot import name 'RFSingleBlocksOverrideNode' from 'ComfyUI-Fluxtapoz.nodes.rf_edit_sampler_nodes' (/home/silver/Playground/AI/ComfyUI/custom_nodes/ComfyUI-Fluxtapoz/nodes/rf_edit_sampler_nodes.py)

Cannot import /home/silver/Playground/AI/ComfyUI/custom_nodes/ComfyUI-Fluxtapoz module for custom nodes: cannot import name 'RFSingleBlocksOverrideNode' from 'ComfyUI-Fluxtapoz.nodes.rf_edit_sampler_nodes' (/home/silver/Playground/AI/ComfyUI/custom_nodes/ComfyUI-Fluxtapoz/nodes/rf_edit_sampler_nodes.py)
```

**Comment by Piscabo** [comment]
Yeah, you broke something else 😒
_Traceback (most recent call last):
  File "H:\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz\__init__.py", line 9, in <module>
    from .nodes.rf_edit_sampler_nodes import FlowEditForwardSamplerNode, FlowEditReverseSamplerNode, PrepareAttnBankNode, RFSingleBlocksOverrideNode, RFDoubleBlocksOverrideNode
ImportError: cannot import name 'RFSingleBlocksOverrideNode' from 'ComfyUI-Fluxtapoz.nodes.rf_edit_sampler_nodes' (H:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz\nodes\rf_edit_sampler_nodes.py)_

**Comment by 925-Studio** [comment]
Seems it has been fixed. Thanks!

> > Hi, sorry for the issue folks, this has been fixed
> 
> Another issue appears after you latest update. Still can't import your custom_node.
> 
> ```shell
> Traceback (most recent call last):
>   File "/home/silver/Playground/AI/ComfyUI/nodes.py", line 2035, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "/home/silver/Playground/AI/ComfyUI/custom_nodes/ComfyUI-Fluxtapoz/__init__.py", line 9, in <module>
>     from .nodes.rf_edit_sampler_nodes import FlowEditForwardSamplerNode, FlowEditReverseSamplerNode, PrepareAttnBankNode, RFSingleBlocksOverrideNode, RFDoubleBlocksOverrideNode
> ImportError: cannot import name 'RFSingleBlocksOverrideNode' from 'ComfyUI-Fluxtapoz.nodes.rf_edit_sampler_nodes' (/home/silver/Playground/AI/ComfyUI/custom_nodes/ComfyUI-Fluxtapoz/nodes/rf_edit_sampler_nodes.py)
> 
> Cannot import /home/silver/Playground/AI/ComfyUI/custom_nodes/ComfyUI-Fluxtapoz module for custom nodes: cannot import name 'RFSingleBlocksOverrideNode' from 'ComfyUI-Fluxtapoz.nodes.rf_edit_sampler_nodes' (/home/silver/Playground/AI/ComfyUI/custom_nodes/ComfyUI-Fluxtapoz/nodes/rf_edit_sampler_nodes.py)
> ```
